### PR TITLE
Fix SKIF not recognizing D3D8/DDraw local injection

### PR DESCRIPTION
**Pull request by Nustat0**

### CODE REVIEW

**Comment by Aemony** [comment]
I think I didn't implement checks for these initially were due to Special K not supporting them out of the box, but relied/required third-party projects to actually be able to do something.

It might be worth implementing an additional check for the presence of e.g. dgVoodoo or similar as well? 🤔

**Comment by Nustat0** [comment]
D3D8/DDraw games require dgVoodoo DLLs to be copied to `PlugIns\ThirdParty\dgVoodoo`.

Apparently SK already has a check for the presence of dgVoodoo:
https://github.com/SpecialKO/SpecialK/blob/3cebf16b3deb2b099af66d72e61b46000ee751b1/src/diagnostics/compatibility.cpp#L327-L338

However, the message about missing dgVoodoo DLLs is not showing for me after I tried deleting `PlugIns\ThirdParty\dgVoodoo` folder. 🤔

**Comment by Nustat0** [comment]
> However, the message about missing dgVoodoo DLLs is not showing for me after I tried deleting `PlugIns\ThirdParty\dgVoodoo` folder. 🤔

Oh, this message only appears in SK Compatibility Layer Prompt after selecting Direct3D8/DirectDraw and clicking Install Wrapper DLL.

I guess it's worth implementing dgVoodoo check in SKIF 🙂

**Comment by Aemony** [comment]
I actually forgot that this is sort of critical even for scenarios without dgVoodoo involved since the global injector will load local wrappers in games that might otherwise not load them.

The behaviour that's described here (but in reality concerns all local wrapper DLL filenames):
https://wiki.special-k.info/en/SpecialK/Local#using-dinput8dll-in-games-that-does-not-natively-load-it

These optional local filenames, `ddraw.dll`, `d3d8.dll`, `dinput8.dll` can all be used as the injection method provided the global injector is used and the game otherwise uses a supported render API.

**Comment by Aemony** [comment]
Thanks for this pull request btw -- when going through the changes I also noticed how none of SKIF's DLL checks were actually case insensitive, and that the Monitor tab had a bug super long that actually prevented locally injected games from being properly detected as injected on the first refresh... 😅

Quite hilarious oversights in hindsight.

**Pull request merged**
